import type { Metadata } from 'next';
import Providers from '@/app/providers';
import localFont from 'next/font/local';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const sfProDisplayRegular = localFont({
	src: '/fonts/SFProDisplay-Regular.woff2',
	weight: '400',
	style: 'normal',
	variable: '--font-sfprodisplay-regular',
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${sfProDisplayRegular.className} antialiased text-[var(--color-black)] bg-[var(--color-white)]`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
