import { findAllProducts, updateProduct } from '@/products/db';
import OpenAI from 'openai';
import pLimit from 'p-limit';

const client = new OpenAI();

const INTERESTS = [
  "Action and Adventure Movies",
  "Action Video Games",
  "Adult Education",
  "Adventure Travel",
  "Adventure Video Games",
  "Alternative Medicine",
  "Alternative Music",
  "Alternative Rock",
  "American Football",
  "Angel Investment",
  "Animals/Pets",
  "Animation Movies",
  "Antiquing and Antiques",
  "Archery",
  "Art",
  "Artificial Intelligence",
  "Arts and Crafts",
  "Astronomy",
  "Audio Production",
  "Augmented Reality",
  "Australian Rules Football",
  "Auto Buying and Selling",
  "Auto Racing",
  "Auto Shows",
  "Auto Technology",
  "Automobiles",
  "Badminton",
  "Baseball",
  "Basketball",
  "BBQ",
  "Beach Volleyball",
  "Beadwork",
  "Beauty",
  "Beekeeping",
  "Biking",
  "Biographies",
  "Bioinformatics",
  "Biology",
  "Birds",
  "Birdwatching",
  "Blogging",
  "Blues",
  "Board Games",
  "Body Art",
  "Bodybuilding",
  "Literature",
  "Bowling",
  "Boxing",
  "Budget Cars",
  "Business",
  "Accounting & Finance",
  "Business and Finance",
  "Calligraphy",
  "Camping",
  "Candle and Soap Making",
  "Canoeing and Kayaking",
  "Car Culture",
  "Car Racing",
  "Card Games",
  "Career Advice",
  "Career Planning",
  "Casual Games",
  "Cats",
  "Cheerleading",
  "Chemistry",
  "Chess",
  "Children's Clothing",
  "Children's Literature",
  "Children's Music",
  "Civil Rights",
  "Classic Cars",
  "Classic Hits",
  "Classic Rock",
  "Classical Music",
  "Climbing",
  "Clinical Science",
  "Cloud Computing",
  "Coding",
  "Collecting",
  "College Baseball",
  "College Basketball",
  "College Football",
  "College Radio",
  "College Sports",
  "Comedy Movies",
  "Comic Books",
  "Comics and Graphic Novels",
  "Computing",
  "Concept Cars",
  "Consumer Electronics",
  "Top 40 Music",
  "Content Production",
  "Cookbooks",
  "Cooking",
  "Counseling",
  "Country Music",
  "Crafting",
  "Cricket",
  "Crime and Mystery Movies",
  "Critical Thinking",
  "Cryptocurrency",
  "Cycling",
  "Dance",
  "Dance and Electronic Music",
  "Dancing",
  "Darts",
  "Dash Cam Videos",
  "Design",
  "Designer Clothing",
  "Desserts and Baking",
  "Digital Art",
  "Digital Arts",
  "Disabled Sports",
  "Diving",
  "DIY Projects",
  "Documentary Movies",
  "Dogs",
  "Drama Movies",
  "Drawing and Sketching",
  "Driverless Cars",
  "Economics",
  "Education",
  "Educational Video Games",
  "Electrical Engineering",
  "Environmental Science and Sustainability",
  "Environmentalism",
  "Equine Sports",
  "eSports",
  "Exercise and Fitness Video Games",
  "Extreme Sports",
  "Family and Children Movies",
  "Fantasy Movies",
  "Fantasy Sports",
  "Fashion",
  "Fashion Trends",
  "Fiction",
  "Field Hockey",
  "Figure Skating",
  "Fine Art Photography",
  "Fish and Aquariums",
  "Fishing",
  "Fitness",
  "Freelance Writing",
  "Frugal Living",
  "Games and Puzzles",
  "Gaming",
  "Gardening",
  "Genealogy",
  "Genetics",
  "Geocaching",
  "Geography",
  "Geology",
  "Golf",
  "Gospel Music",
  "Governance and Society",
  "Green Vehicles",
  "Gymnastics",
  "Hard Rock",
  "Health",
  "Healthy Cooking and Eating",
  "Healthy Living",
  "Herbs and Supplements",
  "High Fashion",
  "Hiking",
  "Hip Hop Music",
  "History",
  "Holistic Health",
  "Home Entertaining",
  "Home Improvement",
  "Horror Movies",
  "Horse Racing",
  "Horseback Riding",
  "Horses and Equine",
  "Human Resources",
  "Human Rights",
  "Humor and Satire",
  "Hunting and Shooting",
  "Ice Hockey",
  "Improv Comedy",
  "Indie and Arthouse Movies",
  "Inline Skating",
  "Inspirational/New Age Music",
  "Insurance",
  "Interior Decorating",
  "Interior Design",
  "International Relations",
  "Internet",
  "Internet of Things",
  "Investing",
  "IT and Internet Support",
  "Jazz",
  "Jewelry Making",
  "Juggling",
  "Kayaking",
  "Kickboxing",
  "Knitting",
  "Lacrosse",
  "Landscaping",
  "Language Learning",
  "Languages",
  "Large Animals",
  "Law",
  "Leadership",
  "Life Sciences",
  "Logistics",
  "Luxury Cars",
  "Magic and Illusion",
  "Marketing and Advertising",
  "Martial Arts",
  "Mechanical Engineering",
  "Medicine and Healthcare",
  "Meditation",
  "Men's Fashion",
  "Men's Health",
  "Mergers and Acquisitions",
  "MMOs",
  "Mobile Games",
  "Model Toys",
  "Modern Art",
  "Motorcycle Sports",
  "Motorcycles",
  "Motorcycling",
  "Mountain Climbing",
  "Movies",
  "Music",
  "Music and Art",
  "Music and Audio",
  "Musical Instruments",
  "Needlework",
  "News and Politics",
  "News Radio",
  "News/Talk Radio",
  "Non-Alcoholic Beverages",
  "Nutrition",
  "Oldies/Adult Standards",
  "Olympic Sports",
  "Online Education",
  "Opera",
  "Origami",
  "Outdoor Decorating",
  "Paintball",
  "Painting",
  "Paranormal Phenomena",
  "Parenting",
  "PC Games",
  "Performance Cars",
  "Personal Care",
  "Personal Finance",
  "Personal Investing",
  "Pet Adoptions",
  "Pets",
  "Philosophy",
  "Photography",
  "Physical Therapy",
  "Physics",
  "Piano",
  "Podcasts",
  "Poetry",
  "Poker and Professional Gambling",
  "Politics",
  "Pop Culture",
  "Pottery",
  "Product Management",
  "Programming Languages",
  "Psychology",
  "Public Radio",
  "Puzzle Video Games",
  "Quilting",
  "R&B/Soul/Funk",
  "Radio Control",
  "RC Vehicles",
  "Reading",
  "Real Estate",
  "Reggae",
  "Religious Music",
  "Remodeling & Construction",
  "Remote Working",
  "Reptiles",
  "Research Methods",
  "Research Paper Writing",
  "Retirement Planning",
  "Robotics",
  "Rock Climbing",
  "Rock Music",
  "Rodeo",
  "Role-Playing Video Games",
  "Roleplaying Games",
  "Rollerblading",
  "Romance Movies",
  "Rowing",
  "Rugby",
  "Rugby League",
  "Rugby Union",
  "Running",
  "Running and Jogging",
  "Sailing",
  "Sales",
  "Sci-fi and Fantasy",
  "Science Fiction Movies",
  "Scooters",
  "Scrapbooking",
  "Screenwriting",
  "Scuba Diving",
  "Sculpture",
  "Sewing",
  "Shopping",
  "Simulation Video Games",
  "Skateboarding",
  "Skiing",
  "Skydiving",
  "Smart Home",
  "Billiards",
  "Snowboarding",
  "Soap Making",
  "Soccer",
  "Social Networking",
  "Social Sciences",
  "Soft Rock",
  "Softball",
  "Songwriters",
  "Showtunes",
  "Space and Astronomy",
  "Sports",
  "Sports Equipment",
  "Sports Radio",
  "Sports Video Games",
  "Squash",
  "Stamp Collecting",
  "Stamps and Coins",
  "Stand-Up Comedy",
  "Startups",
  "Statistics",
  "Storytelling",
  "Strategy Video Games",
  "Street Style",
  "Style & Fashion",
  "Summer Olympic Sports",
  "Surfing",
  "Surfing and Bodyboarding",
  "Swimming",
  "Table Tennis",
  "Tai Chi",
  "Talk Radio",
  "Technology",
  "Television",
  "Tennis",
  "Theater",
  "Track and Field",
  "Travel",
  "Travel Books",
  "Traveling",
  "Upcycling",
  "Urban Contemporary Music",
  "Variety (Music and Audio)",
  "Vegan Diets",
  "Vegetarian Diets",
  "Venture Capital",
  "Video Games",
  "Video Production",
  "Videography",
  "Virtual Reality",
  "Vocational Training",
  "Volleyball",
  "Volunteering",
  "Walking",
  "Watching Documentaries",
  "Water Polo",
  "Waterskiing and Wakeboarding",
  "Weather",
  "Web Development",
  "Web Hosting",
  "Weight Loss",
  "Weightlifting",
  "Wellness",
  "Whittling",
  "Wine Tasting",
  "Winter Olympic Sports",
  "Women's Fashion",
  "Women's Health",
  "Woodworking",
  "Workshops and Classes",
  "World Cuisines",
  "World Movies",
  "World/International Music",
  "Wrestling",
  "Writing",
  "Yoga",
  "Young Adult Literature",
  "Skifahren",
  "Mountains",
  "Ski",
  "WordPress",
  "Gravatar",
  "Figma",
  "CSS",
  "Coffee",
  "Sociology",
  "PHP",
  "Retro",
  "Football",
  "Fussball",
  "wildlife",
  "Nature",
  "Gadgets",
  "entrepreneurship",
  "cybersecurity",
  "linux",
  "open source",
  "Formula 1",
  "Dinosaurs",
  "Ecommerce",
  "Web design",
  "SEO",
  "relationships",
  "Code",
  "AI",
  "B2B",
  "SaaS",
  "E-Commerce",
  "backend",
  "graphic design",
  "Concerts",
  "Software",
  "Java",
  "node.js",
  "Film",
  "Generative AI",
  "Digital Marketing",
  "Search Engine Optimization",
  "Architecture",
  "Anime",
  "Manga",
  "Machine Learning",
  "Python",
  "C",
  "Data Science",
  "Tarot",
  "Jesus",
  "mental health",
  "Server",
  "Cosplay",
  "Health and Wellness",
  "Skin Care",
  "Linguistics",
  "Tecnologia",
  "Nature photography",
  "Ecology",
  "Data Analysis",
  "Software development",
  "Mathematics",
  "Software Engineering",
  "social media",
  "Musica",
  "Acting",
  "Amateur Radio",
  "Food",
  "Pizza",
  "technical SEO",
  "Innovation",
  "shopify",
  "web3",
  "blockchain",
  "LGBTQ",
  "Journalism",
  "drones",
  "sleeping",
  "Tattoos",
  "Climate change",
  "Accessibility",
  "NBA",
  "slot gacor",
  "Game Development",
  "Online business",
  "Illustration",
  "Dubai",
  "Strategy",
  "Risk Management",
  "Finance",
  "Information Technology",
  "Investment",
  "Software As A Service",
  "Stocks",
  "Compliance",
  "Pokemon",
  "Teaching",
  "News",
  "branding",
  "DevOps",
  "Cartoons",
  "Thrifting",
  "Deep Learning",
  "Project Management",
  "NFL",
  "Computers",
  "Lego",
  "Fintech",
  "Data",
  "Ethereum",
  "Minecraft",
  "UI Design",
  "UX Design",
  "Boating",
  "money",
  "culture",
  "Animation",
  "HTML",
  "Nintendo",
  "Mountain Biking",
  "CONSULTING",
  "Books",
  "laravel",
  "drawing",
  "Programming",
  "Family",
  "Coaching",
  "Mentoring",
  "Author",
  "security",
  "Digital transformation",
  "Problem Solving",
  "Public Speaking",
  "JavaScript",
  "TypeScript",
  "Content Marketing",
  "Astrology",
  "Privacy",
  "React",
  "Mythology",
  "Drums",
  "networking",
  "Science",
  "Songwriting",
  "Manufacturing",
  "Websites",
  "Product Design",
  "Creative Writing",
  "Bike",
  "Metal Music",
  "Apple",
  "Tea",
  "Youtube",
  "Computer Science",
  "Wellbeing",
  "aws",
  "terraform",
  "docker",
  "Music Production",
  "Analytics",
  "Automation",
  "growth",
  "learning",
  ".NET",
  "Rust",
  "Creativity",
  "Affiliate marketing",
  "mobile app development",
  "animals",
  "WooCommerce",
  "Entertainment",
  "Outdoors",
  "Adventure",
  "homesteading",
  "star wars",
  "marketing",
  "LLM",
  "Quantum Mechanics",
  "3D Printing",
  "Aviation",
  "Computer Vision",
  "guitar",
  "CrossFit",
  "Video",
  "Japanese",
  "Kotlin",
  "love",
  "Editing",
  "Makeup",
  "Christianity",
  "Driving",
  "DNS",
  "exercise",
  "Composing",
  "Singing",
  "Kids",
  "Azure",
  "Libros",
  "Cultura",
  "Films",
  "Religion",
  "ChatGpt",
  "activism",
  "3D modeling",
  "Flutter",
  "neurodiversity",
  "self improvement",
  "Construction",
  "Git",
  "Faith",
  "Google Ads",
  "Social Media Marketing",
  "Lead Generation",
  "Events",
  "SQL",
  "Pickleball",
  "Spirituality",
  "Copywriting",
  "Logo design",
  "consciousness",
  "Community",
  "Email marketing",
  "Tourism",
  "Karate",
  "Cyber Security",
  "ethical hacking",
  "content writing",
  "mindset",
  "Content Creation",
  "Anthropology",
  "Tech",
  "Angular",
  "Embroidery",
  "Crocheting",
  "Japan",
  "Streaming",
  "Lifestyle",
  "Hacking",
  "God",
  "cleaning",
  "Unity",
  "Mindfulness",
  "Backpacking",
  "IoT",
  "Trade",
  "roblox",
  "Health Supplements",
  "Nutritions",
  "Daily Essentials",
  "Sport",
  "Personal development",
  "Furniture",
  "Hardware",
  "Heavy Metal",
  "Travelling",
  "Trading",
  "Windows",
  "translation",
  "Motherhood",
  "Journaling",
  "sleep",
  "English",
  "crochet",
  "Cinema",
  "cars",
  "Cannabis",
  "Video Editing",
  "communication",
  "sound design",
  "Geopolitics",
  "home decor",
  "podcasting",
  "Cine",
  "peace",
  "Marvel",
  "website design",
  "Trekking",
  "arts",
  "CSharp",
  "Elementor",
  "Freelancing",
  "Financial Services",
  "Advocacy",
  "MySQL",
  "Retail",
  "Productivity",
  "plumbing",
  "DJing",
  "Friends",
  "TTRPGs",
  "Neuroscience",
  "Kpop",
  "Hospitality",
  "Sustainability",
  "Small Business",
  "public relations",
  "Agriculture",
  "Django",
  "Games",
  "GYM",
  "Hunting",
  "Electronics",
  "Bitcoin",
  "webdesign",
  "Kubernetes",
  "Theology",
  "Plants",
  "movie",
  "IT",
  "Farming",
  "Pilates",
  "Reiki",
  "islam",
  "Local SEO",
  "Bible Study",
  "Musicals",
  "True Crime",
  "Dungeons and Dragons",
  "Fediverse",
  "TV Shows",
  "Website Development",
  "frontend",
  "Series",
  "NextJS",
  "Prayer",
  "Wedding",
  "Filmmaking",
  "Disney",
  "PostgreSQL",
  "Church",
  "VUE",
  "media",
  "Publishing",
  "Science Fiction",
  "Reading books",
  "IA",
  "Vlogging",
  "Recipes",
  "Engineering",
  "Research",
  "Photoshop",
  "Radio",
  "lecture",
  "Quantum physics",
  "comedy",
  "live music",
  "baking",
  "Therapy",
  "Higher Education",
  "Business Growth",
  "oil change",
];

const GPT4_INPUT_PRICE_PER_1M = 0.2;
const GPT4_OUTPUT_PRICE_PER_1M = 0.8;

const products = (await findAllProducts()).filter((product) => (product.interests?.length ?? 0) === 0);

let i = 0;
let totalInputTokens = 0;
let totalOutputTokens = 0;

const limit = pLimit(3);

await Promise.all(products.map(product => limit(async () => {
  console.log(`(${++i}/${products.length}) - ${product.productName} - Processing product`);

  if (product.interests) {
    console.log(`(${i}/${products.length}) - ${product.productName} - Skipping product with interests already calculated`);
    return;
  }

  const instructions = `You are an expert ecommerce analyst. Your task is to analyze product details and generate a list of relevant interests that would appeal to potential customers. Consider the following aspects:
    1. Product category and type
    2. Target audience demographics
    3. Lifestyle and values associated with the product
    4. Related hobbies and activities
    5. Complementary interests
    6. Seasonal or occasion-based interests
    7. Price point implications
    8. Brand positioning and values

    Interests should:
     - be specific but not too niche
     - be 1 or 2 words
     - be specific to an interest a person might have

    Restrict the interests to the following list:
    ${INTERESTS.join("\n-")}

    Here are some wrong inferred interests:
     - Kitchen Accessories
     - Humor Gifts

    Return a JSON array of interests, where each interest is a string. Be specific but not too niche.`;

  const input = JSON.stringify({
    productName: product.productName,
    description: product.description,
    storeName: product.shopName
  });

  const response = await client.responses.create({
    model: 'gpt-4.1-mini',
    instructions,
    input
  });

  // Count input tokens
  const inputTokens = response.usage?.input_tokens ?? 0;
  totalInputTokens += inputTokens;

  // Count output tokens
  const outputTokens = response.usage?.output_tokens ?? 0;
  totalOutputTokens += outputTokens;

  console.log(`(${i}/${products.length}) Token usage for this product:`);
  console.log(`- Input tokens: ${inputTokens}`);
  console.log(`- Output tokens: ${outputTokens}`);
  console.log(`- Estimated cost: $${((inputTokens * GPT4_INPUT_PRICE_PER_1M / 1_000_000) + (outputTokens * GPT4_OUTPUT_PRICE_PER_1M / 1_000_000)).toFixed(4)}`);

  try {
    const interests = JSON.parse(response.output_text.replace(/^```json\n/, '').replace(/\n```$/, ''));
    console.log(`(${i}/${products.length}) - ${product.productName} - Calculated interests`, interests);

    await updateProduct({
      ...product,
      interests,
    });
  } catch (error) {
    console.error(`(${i}/${products.length}) - ${product.productName} - Error calculating interests`, error);
    console.log('--');
    console.log(response.output_text);
    console.log('--');
  }
})));

// Print total usage and cost
console.log('\nTotal token usage:');
console.log(`- Total input tokens: ${totalInputTokens}`);
console.log(`- Total output tokens: ${totalOutputTokens}`);
console.log(`- Total estimated cost: $${((totalInputTokens * GPT4_INPUT_PRICE_PER_1M / 1_000_000) + (totalOutputTokens * GPT4_OUTPUT_PRICE_PER_1M / 1_000_000)).toFixed(4)}`);
